name: "Label Merge Conflicts"
description: 'GitHub Action to automatically label PRs with a "conflict" label'
author: "prince-chrismc"
branding:
  icon: "alert-triangle"
  color: "red"
inputs:
  conflict_label_name:
    description: "label name used to marked PRs with merge conflicts"
    required: true
  github_token:
    description: "GitHub token / secret"
    required: true
  max_retries:
    description: "number of times to retry on a failed mergable check"
    required: false
    default: "5"
  wait_ms:
    description: "miliseconds between retries"
    required: false
    default: "5000"
  detect_merge_changes:
    description: "treat soft changes within the merge commits as conflicts and label accordingly"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
