name: "Label Merge Conflicts"
description: 'Label pull requests with merge conflicts and subtle git-blob merge changes beyond those flagged by GitHub'
author: "prince-chrismc"
branding:
  icon: "git-merge"
  color: "red"
inputs:
  github_token:
    description: "GitHub token or secret personal access token"
    required: true
  conflict_label_name:
    description: "The name of the label which should be used to marked PRs with conflicts"
    required: true
  conflict_comment:
    description: "When present, a comment will be added when adding the conflict label"
    required: false
  detect_merge_changes:
    description: "check that the merge commit is an exact match to the branch and report changes as conflicts"
    required: false
    default: "false"
  max_retries:
    description: "number of times to retry on a failed mergable check"
    required: false
    default: "5"
  wait_ms:
    description: "miliseconds between retries"
    required: false
    default: "5000"
runs:
  using: "node16"
  main: "dist/index.js"
