on: 
  workflow_run:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_PAT }}
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: test.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: git-patch
        path: /tmp
    - run: git apply /tmp/fix.diff --index
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
